// Group controller handles CRUD for groups and member management.
// Only group members can view/modify a group; the creator can delete it.
// Invite-link flow: joinByInviteCode lets any logged-in user join via a short code.

import crypto from 'crypto';
import Group from '../models/Group.js';
import User from '../models/User.js';

// ── Helper ────────────────────────────────────────────────────────────
const populateGroup = (query) =>
  query
    .populate('creator', 'name email avatar')
    .populate('members', 'name email avatar');

// @route GET /api/groups
export const getGroups = async (req, res) => {
  try {
    const groups = await populateGroup(
      Group.find({ members: req.user._id, isActive: true }).sort({ createdAt: -1 })
    );
    res.json(groups);
  } catch (error) {
    res.status(500).json({ message: 'Failed to fetch groups', error: error.message });
  }
};

// @route POST /api/groups
export const createGroup = async (req, res) => {
  try {
    const { name, description, category } = req.body;
    if (!name) return res.status(400).json({ message: 'Group name is required' });

    const group = await Group.create({
      name,
      description,
      category,
      creator: req.user._id,
      members: [req.user._id],
      // inviteCode auto-generated by schema default
    });

    const populated = await populateGroup(Group.findById(group._id));
    res.status(201).json(populated);
  } catch (error) {
    res.status(500).json({ message: 'Failed to create group', error: error.message });
  }
};

// @route GET /api/groups/:id
export const getGroupById = async (req, res) => {
  try {
    const group = await populateGroup(Group.findById(req.params.id));

    if (!group || !group.isActive) {
      return res.status(404).json({ message: 'Group not found' });
    }

    const isMember = group.members.some(
      (m) => m._id.toString() === req.user._id.toString()
    );
    if (!isMember) return res.status(403).json({ message: 'Access denied' });

    res.json(group);
  } catch (error) {
    res.status(500).json({ message: 'Failed to fetch group', error: error.message });
  }
};

// @route POST /api/groups/:id/add-member
export const addMember = async (req, res) => {
  try {
    const { email } = req.body;
    const group = await Group.findById(req.params.id);

    if (!group || !group.isActive) return res.status(404).json({ message: 'Group not found' });
    if (group.creator.toString() !== req.user._id.toString()) {
      return res.status(403).json({ message: 'Only the creator can add members' });
    }

    const userToAdd = await User.findOne({ email });
    if (!userToAdd) return res.status(404).json({ message: 'User not found with that email' });

    const alreadyMember = group.members.some(
      (m) => m.toString() === userToAdd._id.toString()
    );
    if (alreadyMember) return res.status(400).json({ message: 'User is already a member' });

    group.members.push(userToAdd._id);
    await group.save();

    const updated = await populateGroup(Group.findById(group._id));
    res.json(updated);
  } catch (error) {
    res.status(500).json({ message: 'Failed to add member', error: error.message });
  }
};

// @route DELETE /api/groups/:id
export const deleteGroup = async (req, res) => {
  try {
    const group = await Group.findById(req.params.id);
    if (!group || !group.isActive) return res.status(404).json({ message: 'Group not found' });
    if (group.creator.toString() !== req.user._id.toString()) {
      return res.status(403).json({ message: 'Only the creator can delete this group' });
    }

    group.isActive = false;
    await group.save();
    res.json({ message: 'Group deleted successfully' });
  } catch (error) {
    res.status(500).json({ message: 'Failed to delete group', error: error.message });
  }
};

// ── Invite Link Handlers ─────────────────────────────────────────────

// @route GET /api/groups/join/:inviteCode  (protected)
// Any logged-in user can hit this URL. If the code is valid they join the group.
export const joinByInviteCode = async (req, res) => {
  try {
    const group = await populateGroup(
      Group.findOne({ inviteCode: req.params.inviteCode, isActive: true })
    );

    if (!group) {
      return res.status(404).json({ message: 'Invalid or expired invite link' });
    }

    const alreadyMember = group.members.some(
      (m) => m._id.toString() === req.user._id.toString()
    );

    if (!alreadyMember) {
      // Bypass populated doc — use raw update to push userId
      await Group.findByIdAndUpdate(group._id, {
        $addToSet: { members: req.user._id },
      });
      const refreshed = await populateGroup(Group.findById(group._id));
      return res.json({ message: 'Joined successfully', group: refreshed });
    }

    // Already a member — just return the group so the frontend can navigate
    res.json({ message: 'Already a member', group });
  } catch (error) {
    res.status(500).json({ message: 'Failed to join group', error: error.message });
  }
};

// @route POST /api/groups/:id/regenerate-invite  (protected, creator only)
// Generates a fresh invite code, invalidating the old link.
export const regenerateInviteCode = async (req, res) => {
  try {
    const group = await Group.findById(req.params.id);
    if (!group || !group.isActive) return res.status(404).json({ message: 'Group not found' });
    if (group.creator.toString() !== req.user._id.toString()) {
      return res.status(403).json({ message: 'Only the creator can regenerate the invite link' });
    }

    group.inviteCode = crypto.randomBytes(6).toString('hex');
    await group.save();

    res.json({ inviteCode: group.inviteCode });
  } catch (error) {
    res.status(500).json({ message: 'Failed to regenerate invite code', error: error.message });
  }
};
